// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProBook.Services.Database;

#nullable disable

namespace ProBook.Services.Migrations
{
    [DbContext(typeof(ProBookDBContext))]
    [Migration("20251014144941_NotebookCollectionSeedMig")]
    partial class NotebookCollectionSeedMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProBook.Services.Database.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 14, 22, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-Collection",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 14, 21, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Bosnian-Collection",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 14, 11, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-Collection",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 14, 13, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Bosnian-Collection",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 13, 11, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-Collection",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Bosnian-Collection",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ProBook.Services.Database.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("SharedNotebookId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Viewed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("SharedNotebookId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ProBook.Services.Database.Notebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notebooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 13, 19, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 13, 20, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-2",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 13, 19, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-3",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 13, 21, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Bosnian-1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 13, 21, 0, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Bosnian-2",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 14, 19, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-1",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 14, 19, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 14, 19, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-3",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 14, 11, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Bosnian-1",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 14, 23, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Bosnian-2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 10, 14, 22, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-1",
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 10, 14, 22, 49, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-2",
                            UserId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 9, 13, 19, 11, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Math-3",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 10, 14, 19, 55, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Bosnian-1",
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 10, 14, 19, 24, 5, 0, DateTimeKind.Utc),
                            Description = "-",
                            Name = "Bosnian-2",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ProBook.Services.Database.NotebookCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NotebookId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("NotebookId");

                    b.ToTable("NotebookCollections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollectionId = 1,
                            CreatedAt = new DateTime(2025, 10, 11, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 1
                        },
                        new
                        {
                            Id = 2,
                            CollectionId = 1,
                            CreatedAt = new DateTime(2025, 10, 11, 11, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 2
                        },
                        new
                        {
                            Id = 3,
                            CollectionId = 1,
                            CreatedAt = new DateTime(2025, 10, 11, 10, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 3
                        },
                        new
                        {
                            Id = 4,
                            CollectionId = 2,
                            CreatedAt = new DateTime(2025, 10, 10, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 4
                        },
                        new
                        {
                            Id = 5,
                            CollectionId = 2,
                            CreatedAt = new DateTime(2025, 10, 9, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 5
                        },
                        new
                        {
                            Id = 6,
                            CollectionId = 3,
                            CreatedAt = new DateTime(2025, 10, 9, 12, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 6
                        },
                        new
                        {
                            Id = 7,
                            CollectionId = 3,
                            CreatedAt = new DateTime(2025, 10, 6, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 7
                        },
                        new
                        {
                            Id = 8,
                            CollectionId = 3,
                            CreatedAt = new DateTime(2025, 10, 5, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 8
                        },
                        new
                        {
                            Id = 9,
                            CollectionId = 4,
                            CreatedAt = new DateTime(2025, 10, 11, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 9
                        },
                        new
                        {
                            Id = 10,
                            CollectionId = 4,
                            CreatedAt = new DateTime(2025, 10, 1, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 10
                        },
                        new
                        {
                            Id = 11,
                            CollectionId = 5,
                            CreatedAt = new DateTime(2025, 10, 2, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 11
                        },
                        new
                        {
                            Id = 12,
                            CollectionId = 5,
                            CreatedAt = new DateTime(2025, 10, 4, 22, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 12
                        },
                        new
                        {
                            Id = 13,
                            CollectionId = 5,
                            CreatedAt = new DateTime(2025, 6, 11, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 13
                        },
                        new
                        {
                            Id = 14,
                            CollectionId = 6,
                            CreatedAt = new DateTime(2025, 9, 11, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 14
                        },
                        new
                        {
                            Id = 15,
                            CollectionId = 6,
                            CreatedAt = new DateTime(2025, 10, 6, 19, 49, 5, 0, DateTimeKind.Utc),
                            NotebookId = 15
                        });
                });

            modelBuilder.Entity("ProBook.Services.Database.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("NotebookId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NotebookId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("ProBook.Services.Database.SharedNotebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FromUserId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsForEdit")
                        .HasColumnType("boolean");

                    b.Property<int>("NotebookId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SharedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("NotebookId");

                    b.HasIndex("ToUserId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedNotebooks");
                });

            modelBuilder.Entity("ProBook.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool?>("IsStudent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegisteredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@gmail.com",
                            Gender = "Male",
                            IsStudent = true,
                            Name = "User1",
                            PasswordHash = "UbzzxOGag4pPmBhguTkyKnpEZw4=",
                            PasswordSalt = "qYk4OxryQgplthbzFlS0yQ==",
                            RegisteredDate = new DateTime(2025, 10, 13, 19, 49, 5, 0, DateTimeKind.Utc),
                            Surname = "User1",
                            TelephoneNumber = "061-234-444",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@gmail.com",
                            Gender = "Male",
                            IsStudent = true,
                            Name = "User2",
                            PasswordHash = "UbzzxOGag4pPmBhguTkyKnpEZw4=",
                            PasswordSalt = "qYk4OxryQgplthbzFlS0yQ==",
                            RegisteredDate = new DateTime(2025, 10, 13, 19, 49, 5, 0, DateTimeKind.Utc),
                            Surname = "User2",
                            TelephoneNumber = "063-234-444",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@gmail.com",
                            Gender = "Female",
                            IsStudent = true,
                            Name = "User3",
                            PasswordHash = "UbzzxOGag4pPmBhguTkyKnpEZw4=",
                            PasswordSalt = "qYk4OxryQgplthbzFlS0yQ==",
                            RegisteredDate = new DateTime(2025, 10, 13, 19, 49, 5, 0, DateTimeKind.Utc),
                            Surname = "User3",
                            TelephoneNumber = "065-234-444",
                            Username = "user3"
                        });
                });

            modelBuilder.Entity("ProBook.Services.Database.Collection", b =>
                {
                    b.HasOne("ProBook.Services.Database.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProBook.Services.Database.Comment", b =>
                {
                    b.HasOne("ProBook.Services.Database.Page", "Page")
                        .WithMany("Comments")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProBook.Services.Database.SharedNotebook", "SharedNotebook")
                        .WithMany("Comments")
                        .HasForeignKey("SharedNotebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Comments_SharedNotebooks_SharedNotebookId");

                    b.HasOne("ProBook.Services.Database.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("SharedNotebook");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProBook.Services.Database.Notebook", b =>
                {
                    b.HasOne("ProBook.Services.Database.User", "User")
                        .WithMany("Notebooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProBook.Services.Database.NotebookCollection", b =>
                {
                    b.HasOne("ProBook.Services.Database.Collection", "Collection")
                        .WithMany("NotebookCollections")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProBook.Services.Database.Notebook", "Notebook")
                        .WithMany("NotebookCollections")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("ProBook.Services.Database.Page", b =>
                {
                    b.HasOne("ProBook.Services.Database.Notebook", "Notebook")
                        .WithMany("Pages")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("ProBook.Services.Database.SharedNotebook", b =>
                {
                    b.HasOne("ProBook.Services.Database.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProBook.Services.Database.Notebook", "Notebook")
                        .WithMany("SharedNotebooks")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProBook.Services.Database.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProBook.Services.Database.User", null)
                        .WithMany("SharedNotebooks")
                        .HasForeignKey("UserId");

                    b.Navigation("FromUser");

                    b.Navigation("Notebook");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("ProBook.Services.Database.Collection", b =>
                {
                    b.Navigation("NotebookCollections");
                });

            modelBuilder.Entity("ProBook.Services.Database.Notebook", b =>
                {
                    b.Navigation("NotebookCollections");

                    b.Navigation("Pages");

                    b.Navigation("SharedNotebooks");
                });

            modelBuilder.Entity("ProBook.Services.Database.Page", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ProBook.Services.Database.SharedNotebook", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ProBook.Services.Database.User", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Comments");

                    b.Navigation("Notebooks");

                    b.Navigation("SharedNotebooks");
                });
#pragma warning restore 612, 618
        }
    }
}
